services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "TaskBridge@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" 
    volumes: 
      - sqlserver-data:/var/opt/mssql
  
  redis : 
    image: redis:latest
    ports: 
      - "6379:6379" 
  
  rabbitmq : 
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672"
  
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskBridgeDb;User Id=sa;Password=TaskBridge@123;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__RabbitMQ=rabbitmq
    depends_on:
      - sqlserver 
      - redis  
      - rabbitmq
    
volumes: 
    sqlserver-data: